Adding Shorten Station Name option for configuration
morosanmihail/HA-LondonTfL pull request #9
Opened 2022-05-10 20:09 UTC by dwardu89

This is related to Issue #8, I might need some guidance in this.

2022-05-11 09:51 UTC, morosanmihail requested changes

2022-05-11 09:51 UTC, morosanmihail commented on custom_components/london_tfl/sensor.py
> +            return destinationName.replace("Underground Station", "").trim()
Could generalise by having a list (in const.py) of strings to remove, and iterating over them here.

2022-05-11 09:51 UTC, morosanmihail commented on custom_components/london_tfl/sensor.py
> +        if CONF_SHORTEN_STATION_NAMES:
This is wrong. It should be `if self.shortenStationNames`. 
`CONF_SHORTEN_STATION_NAMES` always evaluates to true.

2022-05-11 09:51 UTC, morosanmihail commented on custom_components/london_tfl/sensor.py
> +                    bool(top[CONF_SHORTEN_STATION_NAMES]),
`stop[...` instead of `top[...`

2022-05-11 09:51 UTC, morosanmihail commented on custom_components/london_tfl/sensor.py
> +                    bool(top[CONF_SHORTEN_STATION_NAMES]),
`stop[...` instead of `top[...`

2022-05-11 09:51 UTC, morosanmihail commented
It looks good as a start! A few tiny changes and it'll solve the problem.

2022-05-11 21:35 UTC, dwardu89 commented
@morosanmihail  I've made those changes, have a look and see what you think.

2022-05-11 21:43 UTC, dwardu89 commented
I thought of putting "Station" in however there are some names, such as "Battersea Power Station" which would end up being "Battersea Power" potentially an improvement could be that we have a dictionary list of stations and just do a map replace if the shorten list is there. However that might need some manipulations of the API to get the whole list of how it outputs it.

2022-05-12 23:17 UTC, morosanmihail approved these changes

2022-05-12 23:19 UTC, merged